### ISSUE TITLE
Make refract lib part of the minim project

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd-transactions#10]
Make `refract.coffee` a part of the [refract-query](https://github.com/apiaryio/refract-query) or [minim](https://github.com/refractproject/minim/) projects. Requirements:
#### Ability to add additional information to nodes in the Refract tree

When processing the Refract tree, I find out some information specific to certain elements and I want to save the information back to the tree as _attribute_ or _meta_ value.
#### Get parent elements (or first parent element) of certain type of given node

Usually I'm interested in certain elements deep in the Refract structure. I can do sth like:

```
for transition in <find all transitions>
    for transaction in <find all transactions within transition>
        for request in <find all requests within transaction>
            for x in <find all elements x within request>
                <now I can work with element x and with it's parents>
```

...but that makes my code ugly. What I want to do:

```
for x in <find all elements x>
    <now I can work with element x>
    transaction = <find first transaction in x's parents>
    <now I can work with element x's parents>
```
#### Recognize what is content of given node

Now I have function:

``` coffee
content = (node) ->
  if node?.element then content(node.content) else node
```
#### Find recursively any children elements (or first child element) of certain type within given node (although it's in attributes)

I want to find all subelements of type "source map" for given element (e.g. request). Then I want to manually go through found source maps and do some arithmetic on top of their contents.

```
messageBody = child(httpResponse, {element: 'asset', 'meta.classes': 'messageBody'})

httpResponse = child(httpTransaction, {element: 'httpResponse'})

for httpTransaction in children(parseResult, {element: 'httpTransaction'})
    ...
```

E.g. refract-query looks for elements only in `content`, but source maps are in `attributes`.

**Comment by XVincentX** [comment]
@honzajavorek Do you know what's the status on Minim regarding your specific request? That's exactly what I would need as well for the Visual Studio Code extension

**Comment by honzajavorek** [comment]
@XVincentX Many of these are solvable pretty well with the latest minim. What exactly do you need?

**Comment by kylef** [comment]
I agree, most of this should be solved. There is also https://github.com/refractproject/minim/pull/149 which would make this even better. https://github.com/refractproject/minim/pull/149 makes it simply to search both up and recursively down a refract tree and solve all of these use cases.

**Comment by kylef** [comment]
@XVincentX If you have any other specific suggestions or ideas please create issues on Minim and I'll try addressing them.

**Comment by XVincentX** [comment]
I will - I probably just have to catch up with latest development in minim and see if it's now solving my use cases. Thanks!

**Comment by honzajavorek** [comment]
I think we can actually close this now. https://github.com/apiaryio/dredd-transactions/pull/101 is already a proof everything Dredd needs is possible with minim now. We're just discussing convenience.
