### ISSUE TITLE
Fury dependency not locked here but in other dependencies of dredd

### ISSUE THREAD

**Issue by einSelbst** [apiaryio/dredd-transactions#115]
We're having some issues with dredd on travis and want to bring to your attention that while this package tries to install 

`fury@3.0.0-alpha.5` (-> "fury": "^3.0.0-beta.4",)

other dependencies of 'dredd' are locked to 

`fury@3.0.0-alpha.4`

[fury-adapter-swagger](https://github.com/apiaryio/fury-adapter-swagger/blob/master/package.json) & [fury-adapter-apib-parser](https://github.com/apiaryio/fury-adapter-apib-parser/blob/master/package.json)
```
"peerDependencies": {
    "fury": "3.0.0-beta.4"
  },
```

If you think there is nothing to be done about this feel free to close this issue.

**Comment by honzajavorek** [comment]
I believe this has been fixed in https://github.com/apiaryio/dredd-transactions/pull/118. Thanks! It will take a while until this bubbles up to Dredd, but we're working on it.
