### ISSUE TITLE
Transform CommonJS module syntax to ES Modules syntax (import / export)

### ISSUE THREAD

**Issue by michalholasek** [apiaryio/dredd-transactions#132]
Due to dependency on `proxyquire`, we cannot easily transform / use ES Module syntax and semantics in `dredd-transactions` codebase (other limitations can be resolved by [@std/esm](https://www.npmjs.com/package/@std/esm) package). We need to research / think through how to replace `proxyquire` with some other solution.

**Comment by honzajavorek** [comment]
We'll do this accross Dredd's repositories in the future, but avoiding Babel compilation and using CJS is a pragmatic choice for now. If we ever introduce Babel again to support browsers or if we deprecate all Node versions not supporting ESM in the future, this will become a priority again.
