### ISSUE TITLE
Arrays in parameters don't get their example values extracted correctly

### ISSUE THREAD

**Issue by theomega** [apiaryio/dredd-transactions#64]
When you have a swagger spec which requires an array in the parameters, this doesn't work.
Check [this simple swaggerfile](https://gist.github.com/theomega/b7e9f34f0dad11b92c1cb9de9fc95d32).
If you run dredd against this file none of the two `x-example` are taken. Instead, the url will look like this:
`/hello?aggregates=%5Bobject%20Object%5D`

The full dredd log:

> info: Configuration './dredd.yml' found, ignoring other arguments.
> info: Starting server with command: node index.js
> info: Waiting 3 seconds for server command to start...
> info: Backend server exited
> info: Beginning Dredd testing...
> error: GET /hello?aggregates=%5Bobject%20Object%5D duration: 8ms
> error: Error connecting to server under test!
> info: Displaying failed tests...
> fail: GET /hello?aggregates=%5Bobject%20Object%5D duration: 8ms
> fail: Error connecting to server under test!
> request: 
> method: GET
> uri: /hello?aggregates=%5Bobject%20Object%5D
> headers: 
>     User-Agent: Dredd/2.0.0 (Darwin 15.6.0; x64)
> 
> body: 
> 
> expected: 
> headers: 
> 
> body: 
> 
> statusCode: 200
> bodySchema: {"type":"string"}

**Comment by theomega** [comment]
Just as a sidenote: I think, to fix this, one must add a special handling for arrays (and their collectionFormat perhaps) somewhere in the `compile.coffee` file, maybe around [here][1]

  [1]: https://github.com/apiaryio/dredd-transactions/blob/master/src/compile.coffee#L158

**Comment by honzajavorek** [comment]
Thanks for reporting this! `collectionFormat` isn't actually supported yet as of now (and I'd have to check if arrays as URL parameters are supported at all), but it's not an excuse that you was not informed by Dredd about it.

- It's not implemented yet, so it's a request for improvement.
- As of now, there should be at least a warning or an error clearly stating that this is yet to be implemented, so I'm labeling this as a bug.

You are correct that this needs to be implemented in Dredd Transactions' compile and it may even need some work in the [Fury Swagger adapter](https://github.com/apiaryio/fury-adapter-swagger/).

**Comment by honzajavorek** [comment]
This was actually introduced in Swagger adapter and DT were fixed to support this in https://github.com/apiaryio/dredd-transactions/pull/94. Closing! 🎉 Thanks for the idea, @theomega!
