### ISSUE TITLE
Dredd Transactions are slow

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd-transactions#66]
As reported and investigated in https://github.com/apiaryio/dredd/issues/633#issuecomment-254144262, it seems Dredd Transactions are much slower than it's predcessor, [blueprint-transactions](https://github.com/apiaryio/blueprint-transactions).

**Comment by geekbrother** [comment]
I think its compiler issue, because tests runs quickly, dread hang on 'Compiling HTTP transactions from API description file', even if that file is not so much big.

**Comment by alex-pex** [comment]
Did you make any progress on the slowness? Do you think it's not a dredd-transactions problem, but the way dredd uses it?

**Comment by alex-pex** [comment]
I see compile uses a LOT of time the parent() function (https://github.com/apiaryio/dredd-transactions/blob/5b7f09f1777797451098864257175869e5f6b43e/src/compile.coffee#L188), which is basically a big loop over blueprint parts (https://github.com/apiaryio/dredd-transactions/blob/5b7f09f1777797451098864257175869e5f6b43e/src/refract.coffee#L37)

The compilation is getting slower and slower with big files, so I guess the loop is going further and further before matching parent node.

**Comment by alex-pex** [comment]
Maybe we should traverse only once, in https://github.com/apiaryio/dredd-transactions/blob/master/src/parse.coffee#L40 to set the parent property and never traverse again.

Then refract.coffee should be rewritten to work without traversing
* https://github.com/apiaryio/dredd-transactions/blob/5b7f09f1777797451098864257175869e5f6b43e/src/refract.coffee#L15
* https://github.com/apiaryio/dredd-transactions/blob/5b7f09f1777797451098864257175869e5f6b43e/src/refract.coffee#L37

I tried something but I'm not familiar with coffeescript (I'm a ES6 guy https://github.com/apiaryio/dredd/issues/705)

**Comment by honzajavorek** [comment]
@alex-pex Wow! Thanks a lot for looking into this! I agree the traversals could be the culprit. The reason this is custom code is explained in https://github.com/apiaryio/dredd-transactions/issues/10 and https://github.com/refractproject/minim/issues/99.

First, I'd be interested in what are @apiaryio/descriptions-team's plans with tooling about API Elements. Maybe Fury is awaiting some enhancements and we'd do duplicate work here.

Second, I'd have an offer for you 😏 If you're willing to contribute the optimizations in ES6, I'm willing to start converting dredd-transactions to ES6. I'd make the repository a dual codebase and move the whole `refract.coffee` file and respective tests to ES6 for a beginning. What do you think?

**Comment by pksunkara** [comment]
We are actually planning on some improvements to refract soon.

**Comment by honzajavorek** [comment]
@alex-pex @pksunkara I spoke with @netmilk today and we agreed it would be the best if the solution could be built on top of what Fury returns, i.e. on top of [minim](https://github.com/refractproject/minim/). If there's something missing, let's overcome the limitation by custom code in Dredd Transactions' `refract.coffee` / `refract.js` file and if those parts are going to be written well, they could later be directly adopted by minim. What do you think?

**Comment by pksunkara** [comment]
It depends on what it is. We have already planned out the improvements for minim after a lot of discussion over the past few months. I am almost sure whatever you need is going to be part of that. If not, sure, we can go with what you said.

**Comment by honzajavorek** [comment]
@pksunkara Good! Do you have the plans public somewhere? It could be useful when laying out the work on this issue.

**Comment by alex-pex** [comment]
@honzajavorek I can't promise I will have the time to solve this issue, but I'll look into it for sure.
@pksunkara I share the feeling that it could be solved by minim, using Element methods for example.

**Comment by honzajavorek** [comment]
@alex-pex I've got this from @pksunkara: https://usecanvas.com/pksunkara/refract-summit/2KzPLiOaQIpQZi4Sb9FBAu Should be a basic overview of the changes they laid out for Fury and minim.

**Comment by honzajavorek** [comment]
This is being addressed by the refactoring work @michalholasek and me do at the moment. Dredd Transactions will get completely ported to use minim. This should solve also .

During the gradual refactoring, we need to add complexity at certain places, which makes Dredd Transactions temporarily slower - see 05be1356822f4060bbf3762f63144798f10b2640, but this all should be better once we're fully on minim.

Note: Once we're on minim, we should revert 05be1356822f4060bbf3762f63144798f10b2640. And we should do some benchmarks before closing this.
